# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\TMProject\Forms\dbForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dbDialog(object):
    def setupUi(self, dbDialog):
        dbDialog.setObjectName("dbDialog")
        dbDialog.setWindowModality(QtCore.Qt.WindowModal)
        dbDialog.resize(400, 300)
        dbDialog.setMinimumSize(QtCore.QSize(400, 300))
        dbDialog.setMaximumSize(QtCore.QSize(400, 300))
        dbDialog.setWindowTitle("")
        self.label = QtWidgets.QLabel(dbDialog)
        self.label.setGeometry(QtCore.QRect(107, 9, 181, 16))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dbDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(dbDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(dbDialog)
        self.label_4.setGeometry(QtCore.QRect(10, 154, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(dbDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 185, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(dbDialog)
        self.label_6.setGeometry(QtCore.QRect(10, 212, 91, 16))
        self.label_6.setObjectName("label_6")
        self.customerBox = QtWidgets.QComboBox(dbDialog)
        self.customerBox.setGeometry(QtCore.QRect(110, 38, 251, 22))
        self.customerBox.setObjectName("customerBox")
        self.taskEdit = QtWidgets.QTextEdit(dbDialog)
        self.taskEdit.setGeometry(QtCore.QRect(110, 70, 251, 71))
        self.taskEdit.setObjectName("taskEdit")
        self.executorBox = QtWidgets.QComboBox(dbDialog)
        self.executorBox.setGeometry(QtCore.QRect(110, 150, 251, 22))
        self.executorBox.setObjectName("executorBox")
        self.dateEditIn = QtWidgets.QDateEdit(dbDialog)
        self.dateEditIn.setGeometry(QtCore.QRect(110, 181, 251, 22))
        self.dateEditIn.setCalendarPopup(True)
        self.dateEditIn.setObjectName("dateEditIn")
        self.dateEditOut = QtWidgets.QDateEdit(dbDialog)
        self.dateEditOut.setGeometry(QtCore.QRect(110, 210, 251, 22))
        self.dateEditOut.setCalendarPopup(True)
        self.dateEditOut.setObjectName("dateEditOut")
        self.horizontalLayoutWidget = QtWidgets.QWidget(dbDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(146, 240, 160, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.addCustomerButton = QtWidgets.QPushButton(dbDialog)
        self.addCustomerButton.setGeometry(QtCore.QRect(370, 37, 21, 23))
        self.addCustomerButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Z:\\TMProject\\Forms\\../icons/add48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addCustomerButton.setIcon(icon)
        self.addCustomerButton.setObjectName("addCustomerButton")
        self.addExecutorButton = QtWidgets.QPushButton(dbDialog)
        self.addExecutorButton.setGeometry(QtCore.QRect(370, 149, 21, 23))
        self.addExecutorButton.setText("")
        self.addExecutorButton.setIcon(icon)
        self.addExecutorButton.setObjectName("addExecutorButton")

        self.retranslateUi(dbDialog)
        QtCore.QMetaObject.connectSlotsByName(dbDialog)

    def retranslateUi(self, dbDialog):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("dbDialog", "Добавить запись"))
        self.label_2.setText(_translate("dbDialog", "Клиент"))
        self.label_3.setText(_translate("dbDialog", "Задача"))
        self.label_4.setText(_translate("dbDialog", "Исполнитель"))
        self.label_5.setText(_translate("dbDialog", "Дата начала"))
        self.label_6.setText(_translate("dbDialog", "Срок исполнения"))
        self.saveButton.setText(_translate("dbDialog", "Сохранить"))
        self.cancelButton.setText(_translate("dbDialog", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dbDialog = QtWidgets.QDialog()
    ui = Ui_dbDialog()
    ui.setupUi(dbDialog)
    dbDialog.show()
    sys.exit(app.exec_())
