# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\TMProject\Forms\guideForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_guideDialog(object):
    def setupUi(self, guideDialog):
        guideDialog.setObjectName("guideDialog")
        guideDialog.setWindowModality(QtCore.Qt.WindowModal)
        guideDialog.resize(400, 300)
        guideDialog.setMinimumSize(QtCore.QSize(400, 300))
        guideDialog.setMaximumSize(QtCore.QSize(400, 300))
        guideDialog.setWindowTitle("")
        self.label = QtWidgets.QLabel(guideDialog)
        self.label.setGeometry(QtCore.QRect(158, 5, 71, 16))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(guideDialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 381, 211))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.horizontalLayoutWidget = QtWidgets.QWidget(guideDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(136, 257, 131, 30))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Z:\\TMProject\\Forms\\../icons/add48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.editButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.editButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Z:\\TMProject\\Forms\\../icons/edit48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editButton.setIcon(icon1)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)
        self.delButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.delButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Z:\\TMProject\\Forms\\../icons/delete48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delButton.setIcon(icon2)
        self.delButton.setObjectName("delButton")
        self.horizontalLayout.addWidget(self.delButton)

        self.retranslateUi(guideDialog)
        QtCore.QMetaObject.connectSlotsByName(guideDialog)

    def retranslateUi(self, guideDialog):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("guideDialog", "Клиенты"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("guideDialog", "Наименование"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    guideDialog = QtWidgets.QDialog()
    ui = Ui_guideDialog()
    ui.setupUi(guideDialog)
    guideDialog.show()
    sys.exit(app.exec_())
